<?xml version="1.0" encoding="utf-8"?><Database Name="as6501h" Class="DataClassesUniversityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql-server;Initial Catalog=as6501h;User ID=as6501h" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="as6501hConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AllStaff" Member="AllStaffs">
    <Type Name="AllStaff">
      <Column Name="AllStaffID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AllStaff_RegisteredStaff" Member="RegisteredStaffs" ThisKey="AllStaffID" OtherKey="AllStaffID" Type="RegisteredStaff" />
      <Association Name="Department_AllStaff" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
      <Association Name="Role_AllStaff" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClosureDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Category_DepartmentCategory" Member="DepartmentCategories" ThisKey="CategoryID" OtherKey="CategoryID" Type="DepartmentCategory" />
      <Association Name="Category_Idea" Member="Ideas" ThisKey="CategoryID" OtherKey="CategoryID" Type="Idea" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Comment" Member="Comment1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IdeaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegisteredStaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAnnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Idea_Comment" Member="Idea" ThisKey="IdeaID" OtherKey="IdeaID" Type="Idea" IsForeignKey="true" />
      <Association Name="RegisteredStaff_Comment" Member="RegisteredStaff" ThisKey="RegisteredStaffID" OtherKey="RegisteredStaffID" Type="RegisteredStaff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartementName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Department_AllStaff" Member="AllStaffs" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="AllStaff" />
      <Association Name="Department_DepartmentCategory" Member="DepartmentCategories" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="DepartmentCategory" />
    </Type>
  </Table>
  <Table Name="dbo.DepartmentCategory" Member="DepartmentCategories">
    <Type Name="DepartmentCategory">
      <Column Name="DepartmentCategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Category_DepartmentCategory" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="Department_DepartmentCategory" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Document" Member="Documents">
    <Type Name="Document">
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdeaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DocPath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Idea_Document" Member="Idea" ThisKey="IdeaID" OtherKey="IdeaID" Type="Idea" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Idea" Member="Ideas">
    <Type Name="Idea">
      <Column Name="IdeaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RegisteredStaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAnnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Idea_Comment" Member="Comments" ThisKey="IdeaID" OtherKey="IdeaID" Type="Comment" />
      <Association Name="Idea_Document" Member="Documents" ThisKey="IdeaID" OtherKey="IdeaID" Type="Document" />
      <Association Name="Idea_Rating" Member="Ratings" ThisKey="IdeaID" OtherKey="IdeaID" Type="Rating" />
      <Association Name="Idea_Report" Member="Reports" ThisKey="IdeaID" OtherKey="IdeaID" Type="Report" />
      <Association Name="Category_Idea" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="RegisteredStaff_Idea" Member="RegisteredStaff" ThisKey="RegisteredStaffID" OtherKey="RegisteredStaffID" Type="RegisteredStaff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoginSession" Member="LoginSessions">
    <Type Name="LoginSession">
      <Column Name="LoginSessionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisteredStaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Browser" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RegisteredStaff_LoginSession" Member="RegisteredStaff" ThisKey="RegisteredStaffID" OtherKey="RegisteredStaffID" Type="RegisteredStaff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rating" Member="Ratings">
    <Type Name="Rating">
      <Column Name="RatingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdeaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegisteredStaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Vote" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Idea_Rating" Member="Idea" ThisKey="IdeaID" OtherKey="IdeaID" Type="Idea" IsForeignKey="true" />
      <Association Name="RegisteredStaff_Rating" Member="RegisteredStaff" ThisKey="RatingID" OtherKey="RegisteredStaffID" Type="RegisteredStaff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegisteredStaff" Member="RegisteredStaffs">
    <Type Name="RegisteredStaff">
      <Column Name="RegisteredStaffID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RUsername" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RPassword" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AllStaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="RegisteredStaff_Comment" Member="Comments" ThisKey="RegisteredStaffID" OtherKey="RegisteredStaffID" Type="Comment" />
      <Association Name="RegisteredStaff_Idea" Member="Ideas" ThisKey="RegisteredStaffID" OtherKey="RegisteredStaffID" Type="Idea" />
      <Association Name="RegisteredStaff_LoginSession" Member="LoginSessions" ThisKey="RegisteredStaffID" OtherKey="RegisteredStaffID" Type="LoginSession" />
      <Association Name="RegisteredStaff_Rating" Member="Rating" ThisKey="RegisteredStaffID" OtherKey="RatingID" Type="Rating" Cardinality="One" />
      <Association Name="RegisteredStaff_Report" Member="Reports" ThisKey="RegisteredStaffID" OtherKey="RegisteredStaffID" Type="Report" />
      <Association Name="AllStaff_RegisteredStaff" Member="AllStaff" ThisKey="AllStaffID" OtherKey="AllStaffID" Type="AllStaff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report" Member="Reports">
    <Type Name="Report">
      <Column Name="ReportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisteredStaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdeaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Idea_Report" Member="Idea" ThisKey="IdeaID" OtherKey="IdeaID" Type="Idea" IsForeignKey="true" />
      <Association Name="RegisteredStaff_Report" Member="RegisteredStaff" ThisKey="RegisteredStaffID" OtherKey="RegisteredStaffID" Type="RegisteredStaff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Role_AllStaff" Member="AllStaffs" ThisKey="RoleID" OtherKey="RoleID" Type="AllStaff" />
    </Type>
  </Table>
</Database>